name: PhotosExporterLib CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-15
    steps:
    - name: Select Xcode 16.3
      run: sudo xcode-select -s /Applications/Xcode_16.3.app/Contents/Developer
    - uses: snyk/actions/setup@master
    - uses: actions/checkout@v4
    - name: Build
      run: swift build -v
    - name: Lint
      uses: cirruslabs/swiftlint-action@v1
      with:
        version: latest
    - name: Run tests
      run: swift test -v
    - name: Run Snyk
      run: snyk test --sarif-file-output=snyk.sarif
    - name: Upload Snyk result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: snyk.sarif